from __future__ import annotations

from pathlib import Path

APP_ROOT = Path(__file__).resolve().parent.parent
OUTPUTS_DIR = APP_ROOT / "outputs"
JOBS_DIR = OUTPUTS_DIR / "jobs"
PREPARED_REFERENCES_DIR = OUTPUTS_DIR / "prepared_references"
TRAINING_DATA_DIR = APP_ROOT / "training_data"

DEFAULT_OUTPUT_SAMPLE_RATE = 24_000
DEFAULT_FRAGMENT_PAUSE_MS = 250
DEFAULT_REFERENCE_EXCERPT_SECONDS = 12.0
DEFAULT_REFERENCE_EXCERPT_COUNT = 1
MAX_FRAGMENT_CHARS = 240
MAX_SYNTHESIS_CHARS = 300
MIN_REFERENCE_SECONDS = 3.0
MAX_REFERENCE_SECONDS = 30.0
DEFAULT_XTTS_MODEL = "tts_models/multilingual/multi-dataset/xtts_v2"
DEFAULT_SYNTHESIS_SEED = 42
MAX_RESYNTHESIS_ATTEMPTS = 3
MAX_FIDELITY_CANDIDATES = 3
SPEAKER_SIMILARITY_THRESHOLD = 0.72
SPEAKER_SIMILARITY_WARNING_THRESHOLD = 0.65

REFERENCE_PROFILE_AUTO = "auto"
REFERENCE_PROFILE_SHORT = "short"
REFERENCE_PROFILE_LONG = "long"
REFERENCE_PROFILE_OPTIONS = [REFERENCE_PROFILE_AUTO, REFERENCE_PROFILE_SHORT, REFERENCE_PROFILE_LONG]

FIDELITY_MODE_NORMAL = "normal"
FIDELITY_MODE_MAXIMUM = "maxima"
FIDELITY_MODE_OPTIONS = [FIDELITY_MODE_NORMAL, FIDELITY_MODE_MAXIMUM]

SHORT_PROFILE_CONSOLIDATED_SECONDS = 18.0
SHORT_PROFILE_SEGMENT_COUNT = 3
LONG_PROFILE_CONSOLIDATED_SECONDS = 24.0
LONG_PROFILE_SEGMENT_COUNT = 3

SPEAKER_ADAPTATION_MIN_SECONDS = 600.0
SPEAKER_ADAPTATION_IDEAL_MIN_SECONDS = 900.0
SPEAKER_ADAPTATION_IDEAL_MAX_SECONDS = 1800.0
SPEAKER_PROFILES_DIR = TRAINING_DATA_DIR / "speaker_profiles"

SERVER_HOST = "127.0.0.1"
SERVER_PORT = 7860


def ensure_app_directories() -> None:
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    JOBS_DIR.mkdir(parents=True, exist_ok=True)
    PREPARED_REFERENCES_DIR.mkdir(parents=True, exist_ok=True)
    TRAINING_DATA_DIR.mkdir(parents=True, exist_ok=True)
    SPEAKER_PROFILES_DIR.mkdir(parents=True, exist_ok=True)
